---
services:
  webhook:
    build: .
    container_name: bot
    ports:
      - '8080:8080'
    restart: always
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app/

networks:
  bridge:
    name: bridge
    external: true